Question 4:
Flattening the Terrain: 
Write a function flatten_terrain(terrain_data) that takes a 3D NumPy array representing terrain data (e.g., height at each point) and returns a 2D NumPy array representing the flattened height map.

In [12]:
import numpy as np

def flatten_terrain(terrain_data):
    # Reshape 3D terrain data into 2D array and extract height values
    return terrain_data.reshape(-1, terrain_data.shape[0])[:, 0]

terrain_data = np.random.rand(3, 4, 2)  # Replace with your 3D terrain data
print("Terrain Data in 3D: \n",terrain_data,"\n")
flattened_terrain = flatten_terrain(terrain_data)
print("Terrain data after reshaping in 2D: \n",flattened_terrain)


Terrain Data in 3D: 
 [[[0.31980731 0.16853798]
  [0.58612734 0.09148729]
  [0.3254592  0.64847361]
  [0.2214044  0.06117965]]

 [[0.85619854 0.03973761]
  [0.16909473 0.5170487 ]
  [0.24829384 0.2123534 ]
  [0.50115921 0.81462207]]

 [[0.66347315 0.61564462]
  [0.83847902 0.55337561]
  [0.55612573 0.23690341]
  [0.85690218 0.06865104]]] 

Terrain data after reshaping in 2D: 
 [0.31980731 0.09148729 0.2214044  0.03973761 0.24829384 0.81462207
 0.83847902 0.23690341]
